[phases.setup]
nixPkgs = ["nodejs_20", "caddy"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]
# Las variables de entorno VITE_* se pasan automáticamente desde Easypanel

[start]
cmd = "caddy run --config /app/Caddyfile --adapter caddyfile"

